config/routes.rb
OurnaropaLibrary::Engine.routes.draw do
  
  get '/search', to: 'search#show', as: :search
  
  get '/fetch_results/:school/:query', to: 'search#fetch_results', as: :fetch_results
  
  root 'search#index', as: :home
  
end

app/controllers/ournaropa_library/application_controller.rb
module OurnaropaLibrary
  class ApplicationController < ActionController::Base
  end
end

app/controllers/ournaropa_library/search_controller.rb
require_dependency "ournaropa_library/application_controller"

module OurnaropaLibrary
  class SearchController < ::ApplicationController
    
    require "uri"

    # inherit the layout from the main application
    layout 'application'
    
    def index
      @search_naropa = true
      @search_cu = true
      @search_bpl = true
    end
    
    # GET /search/QUERY
    def show
            
      @query = params[:query]
      
      if @query.blank?
        redirect_to home_path
      else 
        
        @search_naropa  = params[:naropa].present? ? params[:naropa] : false
        @search_cu      = params[:cu].present? ? params[:cu] : false
        @search_bpl     = params[:bpl].present? ? params[:bpl] : false


        # if all three are false, then the user must have forgotten to put in the search libraries --- we'll search all three
        if @search_naropa == false && @search_cu == false && @search_bpl == false
          @search_naropa = @search_cu = @search_bpl = true
        end

        render :show 
        
      end
    end  
    
    
    # search Naropa
    def fetch_results
      
      @query = URI.encode params[:query]
      @school = params[:school]
      
      puts case @school
      when "naropa"
        @link_to_results = "http://howlcat.naropa.edu/cgi-bin/koha/opac-search.pl?q=#{@query}&branch_group_limit="
        @results = fetch_from_naropa @link_to_results
      when "cu"
        @link_to_results = "http://encore.colorado.edu/iii/encore/search/C__S#{@query}__Orightresult__U?lang=eng&suite=cobalt"
        @results = fetch_from_cu @link_to_results
      when "bpl"
        @link_to_results = "http://boulder.flatironslibrary.org/Union/Search?lookfor=#{@query}"
        @results = fetch_from_bpl @link_to_results
      end
        
      respond_to do |format|
       format.js { render :show_results }
      end
      
    end
  
  private
  
    # fetches from Naropa 
    def fetch_from_naropa url
      
      # fetch contents
      content = Nokogiri::HTML(fetch_from_url url)
      
      results = []
      @result_count = 0
      
      # parse results
      if content.css(".bibliocol").present?
        
        # GET NUMBER RESULTS
        @result_count = content.css("#numresults").text
        # cut away useless info
        @result_count = @result_count[0, @result_count.index(' results.')].strip
        # cut away currently showing
        @result_count = @result_count[@result_count.rindex(' ')+1, @result_count.length]
      
        # PARSE RESULTS
        content.css(".bibliocol").each do |result|

          results.push({
            :title => result.css(".title").text,
            :author => result.css(".author").text,
            :availability => result.css(".available").blank? ? result.css(".unavailable").text : result.css(".available").text,
            :url => "http://howlcat.naropa.edu" + result.css(".title").attribute("href").value

            })

        end
      end
      
      return results
      
    end
    
    def fetch_from_bpl url
      
      # fetch contents
      content = Nokogiri::HTML(fetch_from_url url)
        
      results = []
      @result_count = 0
      
      # PARSE RESULTS
      if content.css(".result").present?
        
        # GET NUMBER RESULTS
        @result_count = content.css(".result-head").text
        # cut away query time
        @result_count = @result_count[0, @result_count.index(' query')].strip
        # cut away currently showing
        @result_count = @result_count[@result_count.rindex(' ')+1, @result_count.length]
        
        
        content.css(".result").each do |result|

          availability = "<ul>"

          result.css(".row.related-manifestation").each do |manifestation|
            availability += "<li>" + manifestation.css(".manifestation-format > a:first-of-type").text + ": " + manifestation.css(".manifestation-format + div > .related-manifestation-shelf-status").text + " &mdash; " + manifestation.css(".manifestation-format + div > .smallText").text + "</li>"
          end

          availability += "</ul>"

          results.push({
            :title => result.css(".result-title").text,
            :author => result.css(".resultsList > .row .row:nth-of-type(2) .result-value").text,
            :availability => availability,
            :url => "http://boulder.flatironslibrary.org" + result.css(".result-title").attribute("href").value

            })

        end
      end
      
      return results
      
    end
    
    # search CU library
    def fetch_from_cu url
      
      # fetch contents
      content = Nokogiri::HTML(fetch_from_url url)
            
      results = []
      @result_count = 0
          
      # parse result
      if content.css("#resultsAnyComponent").present?
        
        # GET NUMBER OF RESULTS
        @result_count = content.css("#searchResultsAnyComponent .noResultsHideMessage").text.strip
        # cut away currently showing
        @result_count = @result_count[@result_count.rindex(' ')+1, @result_count.length]

        # PARSE RESULTS
        content.css(".searchResult").each do |result|

          if result.css(".title").present?
         
            results.push({
              :title => result.css(".title:first-of-type").text,
              :author => result.css(".dpBibAuthor").text,
              :availability => result.css(".availabilitySummaryArea").text,
              :url => "http://encore.colorado.edu/" + result.css(".title a").attribute("href").value

              })
          end
            
        end
      end

      return results
      
    end
    
    
    # fetches content from a given url
    def fetch_from_url url
      require "net/http"

      uri = URI.parse(url)

      http = Net::HTTP.new(uri.host, uri.port)
      request = Net::HTTP::Get.new(uri.request_uri)

      request['User-Agent'] = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36 OPR/36.0.2130.46'
      
      response = http.request(request)
        
      return response.body             # => The body (HTML, XML, blob, whatever)
    end

  end
  
end

app/helpers/ournaropa_library/application_helper.rb
module OurnaropaLibrary
  module ApplicationHelper
  end
end

app/helpers/ournaropa_library/search_helper.rb
module OurnaropaLibrary
  module SearchHelper
    
    def full_school_name abbreviation
      puts case abbreviation
        when "naropa"
        return "Naropa University Libraries"
        when "cu"
        return "University of Colorado Boulder Libraries"
        when "bpl"
        return "Boulder Public Library"
      end
    end
    
    def num_results_per_source
      return 10
    end
    
  end
end

app/views/ournaropa_library/search/_form.html.erb
<%= form_tag search_path, :method => :get, :class => "col s12 valign" do %>

    <div class="row title">
      <h1 class="center-align">OurNaropa Library Search</h1>
      <p class="center-align">Search Naropa's libraries, CU's libraries, and the Boulder Public Library all at once.</p>
    </div>

    <div class="row">
      <div class="input-field col s12 l10">
        <i class="material-icons prefix">search</i>
          <%= text_field_tag(:query, @query, :class => "validate", :type => "text") %>
          <%= label_tag :query, "What are you looking for today...?" %>
      </div>
      <div class="col s12 l2 center-align">
        <button type="submit" class="waves-effect waves-light btn-large">Search</button>
      </div>
    </div>



    <div class="row">
      <div class="m12 center-align">
        <%= check_box_tag :naropa, 'true', @search_naropa, :class => "filled-in" %>
        <%= label_tag(:naropa, "Naropa Libraries") %>      

        <div class="row hide-on-large-only"></div>

        <%= check_box_tag :cu, 'true', @search_cu, :class => "filled-in" %>
        <%= label_tag(:cu, "CU Libraries") %> 

        <div class="row hide-on-large-only"></div>

        <%= check_box_tag :bpl, 'true', @search_bpl, :class => "filled-in" %>
        <%= label_tag(:bpl, "Boulder Public Library") %>
      </div>
    </div>


  <% end %>

app/views/ournaropa_library/search/index.html.erb
<div id="library" class="index container">
  <div class="row">
    <div class="valign-wrapper">
      
      <%= render "form" %>
      
    </div>
  </div>

</div>

app/views/ournaropa_library/search/show.html.erb
<div id="library" class="show container">
  <div class="row">
    <div class="valign-wrapper">
      <%= render 'form' %>
    </div>
  </div>
  
  
  <% schools = "naropa", "cu", "bpl" %>

  <div id="results">
    
    <!-- loading stuff -->
    <% schools.each do |school| %>  

      <div class="result result-<%= school %> loading">
        <a>
          <div class="row">
            <h6 class="center-align">Searching <%= full_school_name school %></h6>
            <div class="progress">
              <div class="indeterminate"></div>
            </div>
          </div>
        </a>
      </div>
    
    <% end %>
    
    <!-- nothing found -->
    <% schools.each do |school| %>  

      <div class="result result-<%= school %> none">
        <div class="row">
          <div class="col s12">
            <h5 class="center-align"><i class="material-icons md-36">sentiment_dissatisfied</i> No results found within <%= full_school_name school %>.</h5>
          </div>
        </div>
      </div>
    
    <% end %>
    
    
    <!-- result spaceholders -->    
    <% for i in 0..num_results_per_source - 1 do %>
      <% schools.each do |school| %>  

        <div class="result result-<%= school %> hover-effect empty">
          <a target="_blank" href="">
            <div class="row">
              <div class="col s2 center-align">
                <%= image_tag "ournaropa_library/" + school + '-icon.jpeg', :alt => "icon", :class => "circle responsive-img" %>
              </div>
              <div class="col s10 content">
              </div>
            </div>
          </a>
        </div>

      <% end %>
    <% end %>
    
    <!-- view more results links -->
    <% schools.each do |school| %>  

      <div class="result result-<%= school %> hover-effect more">
        <a class="link" target="_blank" href="">
          <div class="row">
            <div class="col s12">
              <h5 class="center-align"><i class="material-icons md-36">launch</i> View more <%= full_school_name school %> results...</h5>
            </div>
          </div>
        </a>
      </div>
    
    <% end %>

  </div>

</div>  
  
<script type="text/javascript">  
  
  window.setTimeout(function() {
    $("div.title").slideUp(1000);
  }, 300);
  
    
  window.setTimeout(function() {
      $(".valign-wrapper").height($("form").height()+50);
    }, 1000);
  
  window.setTimeout(function() {
  
  // search Naropa
  <% if @search_naropa %>
    $(".result-naropa.loading").show(0);
    $.ajax({
      type: "GET",
      url: '<%= fetch_results_path "naropa", @query %>',
      dataType: "script"
    });
  <% end %>
  
  // search CU
  <% if @search_cu %>
    $(".result-cu.loading").show(0);
    $.ajax({
      type: "GET",
      url: '<%= fetch_results_path "cu", @query %>',
      dataType: "script"
    });
  <% end %>
  
  // search BPL
  <% if @search_bpl %>
    $(".result-bpl.loading").show(0);
    $.ajax({
      type: "GET",
      url: '<%= fetch_results_path "bpl", @query %>',
      dataType: "script"
    });
  <% end %>
  }, 2000);
</script>

app/views/ournaropa_library/search/show_results.js.erb
function show_result(title, author, availability, url) {
    
  $(".result-<%= @school %>.empty .content").first().html(
    "<h5>"+title+"</h5>"
    + "<p>"+author+"</p>"
    + "<p>"+availability+"</p>"
   );
  
  // link
  $(".result-<%= @school %>.empty a").first().attr("href", url);
  
  // enable
  $(".result-<%= @school %>.empty").first().show(0);
  $(".result-<%= @school %>.empty").first().removeClass("empty");
}

// enable view more results
function enable_view_more(url) {
  $(".result-<%= @school %>.more a.link").attr("href", url);
  $(".result-<%= @school %>.more").show(0);
  //console.log("Enabling something");
}

function showResultCount(school, count) {
  $("#"+school+" + label").append(" (" + count + ")");
}


// show result count at top
showResultCount("<%= @school %>", "<%= @result_count %>");

<% # disable loading indicator  %>
$(".result-<%= @school %>.loading").hide(0);

<% if @results.present? %>
  
  // fill in results
  <% @results.each_with_index do |result, index| %>
    
    <% #break this cycle if we have reached the max results
      if index == num_results_per_source
        break
      end %>
  
    show_result("<%= escape_javascript result[:title] %>", "<%= escape_javascript result[:author] %>", "<%= escape_javascript result[:availability].html_safe %>", "<%= escape_javascript result[:url] %>");

  <% end %>
  
  <% # if @results.count > num_results_per_source, then show link to view more results!
    if @results.count > num_results_per_source %>
    enable_view_more("<%= escape_javascript @link_to_results %>");
  <% end %>
  
<% else %>
  $(".result-<%= @school %>.none").show(0);
<% end %>